name: Contracts Test

on:
  push:
    branches:
      - ted-test
      - test
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # You can specify your desired Node.js version

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: cd packages/contracts && yarn

      - name: Run Tests
        run: cd packages/contracts && yarn hardhat test